# Generated by Django 4.2.16 on 2026-03-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corptools', '0130_swap_to_eve_sde'),
    ]

    operations = [
        # Index on last_update_pub_data for ORDER BY in process_corp_histories
        migrations.AlterField(
            model_name='characteraudit',
            name='last_update_pub_data',
            field=models.DateTimeField(
                blank=True, db_index=True, default=None, null=True
            ),
        ),
        # Index on active field for filtering
        migrations.AddIndex(
            model_name='characteraudit',
            index=models.Index(
                fields=['active'],
                name='corptools_charaudit_active_idx',
            ),
        ),
        # Composite index for get_oldest_qs filtering/ordering
        migrations.AddIndex(
            model_name='characteraudit',
            index=models.Index(
                fields=['active', 'last_update_pub_data'],
                name='corptools_charaudit_active_pub_idx',
            ),
        ),
    ]
